name: crypto_insight_flutter
description: A Professional Flutter Web Frontend for the Crypto Insight AI Research Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  fl_chart: ^0.65.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  provider: ^6.1.1
  animations: ^2.0.11
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  pull_to_refresh: ^2.0.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
